# Generated by Django 5.2.15 on 2026-06-30 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('site_address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('problem_description', models.TextField(blank=True)),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='visits/before/')),
                ('work_description', models.TextField(blank=True)),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='visits/after/')),
                ('status', models.CharField(choices=[('pending', 'Pending — Awaiting Assignment'), ('assigned', 'Assigned to Worker'), ('started', 'Started'), ('completed', 'Completed'), ('approved', 'Approved by Customer'), ('rejected', 'Rejected by Customer')], default='pending', max_length=20)),
                ('customer_feedback', models.TextField(blank=True)),
                ('customer_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
