# Generated by Django 5.2.15 on 2026-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_worker_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='category',
            field=models.CharField(choices=[('ac_repair', 'AC Repair'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('general', 'General Service')], default='general', max_length=20),
        ),
    ]
