# Generated by Django 5.2.14 on 2026-06-24 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_latitude', models.FloatField(blank=True, null=True)),
                ('check_in_longitude', models.FloatField(blank=True, null=True)),
                ('check_in_address', models.CharField(blank=True, max_length=255)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.FloatField(blank=True, null=True)),
                ('check_out_longitude', models.FloatField(blank=True, null=True)),
                ('check_out_address', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent')], default='present', max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
            },
        ),
    ]
